//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID_Message { get; set; }
        public string Text_Message { get; set; }
        public string Name_User { get; set; }
        public string Name_Chat { get; set; }
    
        public virtual Chatt Chatt { get; set; }
        public virtual User User { get; set; }
    }
}
